### ISSUE TITLE
Exception in thread "org.eclipse.cdt.internal.ui.text.CReconciler" java.lang.VerifyError: Cannot inherit from final class

### ISSUE THREAD

**Issue by samba2** [buntatsu/cdt-proc#16]
I'm running on Eclipse Mars .2

I had the plugin working for quite some time - thanks for your effort!

However, in a fresh installation I get the error above.

Reproducing:

New C++ Project > New File > "test.pc"

In the moment the file is created the following message appears:

Screenshot:
![proc_plugin_error_screenshot](https://cloud.githubusercontent.com/assets/1508184/13461473/ebb4841e-e081-11e5-8257-1f1739a6cc63.PNG)

Exception thrown at the the console:
Exception in thread "org.eclipse.cdt.internal.ui.text.CReconciler" java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:272)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:632)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:588)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:540)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:527)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:327)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:402)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at buntatsun.cdt.proc.ProCLanguage.mycreateScanner(ProCLanguage.java:93)
	at buntatsun.cdt.proc.ProCLanguage.getASTTranslationUnit(ProCLanguage.java:104)
	at org.eclipse.cdt.internal.core.model.TranslationUnit.getAST(TranslationUnit.java:876)
	at org.eclipse.cdt.internal.core.model.CModelBuilder2.parse(CModelBuilder2.java:147)
	at org.eclipse.cdt.internal.core.model.TranslationUnit.parseUsingCModelBuilder(TranslationUnit.java:671)
	at org.eclipse.cdt.internal.core.model.TranslationUnit.parse(TranslationUnit.java:659)
	at org.eclipse.cdt.internal.core.model.TranslationUnit.buildStructure(TranslationUnit.java:458)
	at org.eclipse.cdt.internal.core.model.Openable.generateInfos(Openable.java:261)
	at org.eclipse.cdt.internal.core.model.CElement.openWhenClosed(CElement.java:427)
	at org.eclipse.cdt.internal.core.model.TranslationUnit.makeConsistent(TranslationUnit.java:563)
	at org.eclipse.cdt.internal.core.model.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:62)
	at org.eclipse.cdt.internal.core.model.CModelOperation.execute(CModelOperation.java:341)
	at org.eclipse.cdt.internal.core.model.CModelOperation.run(CModelOperation.java:607)
	at org.eclipse.cdt.internal.core.model.CModelOperation.runOperation(CModelOperation.java:635)
	at org.eclipse.cdt.internal.core.model.WorkingCopy.reconcile(WorkingCopy.java:362)
	at org.eclipse.cdt.internal.ui.text.CReconcilingStrategy.reconcile(CReconcilingStrategy.java:78)
	at org.eclipse.cdt.internal.ui.text.CReconcilingStrategy.initialReconcile(CReconcilingStrategy.java:122)
	at org.eclipse.cdt.internal.ui.text.CompositeReconcilingStrategy.initialReconcile(CompositeReconcilingStrategy.java:117)
	at org.eclipse.cdt.internal.ui.text.CCompositeReconcilingStrategy.initialReconcile(CCompositeReconcilingStrategy.java:108)
	at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:105)
	at org.eclipse.cdt.internal.ui.text.CReconciler.initialProcess(CReconciler.java:338)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:173)

Creating "test.c" works without a problem.

Here is my Eclipse config:
[samba2_eclipse_config.txt](https://github.com/buntatsu/cdt-proc/files/154844/samba2_eclipse_config.txt)

**Comment by samba2** [comment]
dublicated, the right version is no 17
