### ISSUE TITLE
Exception in thread "org.eclipse.cdt.internal.ui.text.CReconciler" java.lang.VerifyError: Cannot inherit from final class

### ISSUE THREAD

**Issue by samba2** [buntatsu/cdt-proc#17]
I'm running on Eclipse Mars .2

I had the plugin working for quite some time - thanks for your effort!

However, in a fresh installation I get the error above.

Reproducing:

New C++ Project > New File > "test.pc"

In the moment the file is created the following message appears:

![proc_plugin_error_screenshot](https://cloud.githubusercontent.com/assets/1508184/13461473/ebb4841e-e081-11e5-8257-1f1739a6cc63.PNG)

Exception thrown at the the console:
Exception in thread "org.eclipse.cdt.internal.ui.text.CReconciler" java.lang.VerifyError: Cannot inherit from final class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:272)
    at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:632)
    at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:588)
    at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:540)
    at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:527)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
    at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:327)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:402)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at buntatsun.cdt.proc.ProCLanguage.mycreateScanner(ProCLanguage.java:93)
    at buntatsun.cdt.proc.ProCLanguage.getASTTranslationUnit(ProCLanguage.java:104)
    at org.eclipse.cdt.internal.core.model.TranslationUnit.getAST(TranslationUnit.java:876)
    at org.eclipse.cdt.internal.core.model.CModelBuilder2.parse(CModelBuilder2.java:147)
    at org.eclipse.cdt.internal.core.model.TranslationUnit.parseUsingCModelBuilder(TranslationUnit.java:671)
    at org.eclipse.cdt.internal.core.model.TranslationUnit.parse(TranslationUnit.java:659)
    at org.eclipse.cdt.internal.core.model.TranslationUnit.buildStructure(TranslationUnit.java:458)
    at org.eclipse.cdt.internal.core.model.Openable.generateInfos(Openable.java:261)
    at org.eclipse.cdt.internal.core.model.CElement.openWhenClosed(CElement.java:427)
    at org.eclipse.cdt.internal.core.model.TranslationUnit.makeConsistent(TranslationUnit.java:563)
    at org.eclipse.cdt.internal.core.model.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:62)
    at org.eclipse.cdt.internal.core.model.CModelOperation.execute(CModelOperation.java:341)
    at org.eclipse.cdt.internal.core.model.CModelOperation.run(CModelOperation.java:607)
    at org.eclipse.cdt.internal.core.model.CModelOperation.runOperation(CModelOperation.java:635)
    at org.eclipse.cdt.internal.core.model.WorkingCopy.reconcile(WorkingCopy.java:362)
    at org.eclipse.cdt.internal.ui.text.CReconcilingStrategy.reconcile(CReconcilingStrategy.java:78)
    at org.eclipse.cdt.internal.ui.text.CReconcilingStrategy.initialReconcile(CReconcilingStrategy.java:122)
    at org.eclipse.cdt.internal.ui.text.CompositeReconcilingStrategy.initialReconcile(CompositeReconcilingStrategy.java:117)
    at org.eclipse.cdt.internal.ui.text.CCompositeReconcilingStrategy.initialReconcile(CCompositeReconcilingStrategy.java:108)
    at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:105)
    at org.eclipse.cdt.internal.ui.text.CReconciler.initialProcess(CReconciler.java:338)
    at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:173)

Creating "test.c" works without a problem.

Here is my Eclipse config:
[samba2_eclipse_config.txt](https://github.com/buntatsu/cdt-proc/files/154844/samba2_eclipse_config.txt)

**Comment by samba2** [comment]
To precise my bug report: 
The error happens only with the new CDT 8.8.1 released end for February 2016

I forced my installation back to 8.8.0 and the ProC Plugin is working again. Here is how to do it on the command line if you have naked Eclipse (Eclipse SDK):
```
eclipse -noSplash -purgeHistory \
-application org.eclipse.equinox.p2.director \
-repository http://download.eclipse.org/releases/mars/ \
-installIU org.eclipse.cdt.feature.group/8.8.0.201509131935

```

**Comment by buntatsu** [comment]
cdt_8_8_pub-1.0 works with only CDT 8.8.0.
Please waiting for the 'Modified cdt-core for CDT 8.8.1' release.

**Comment by samba2** [comment]
Dear Buntatsu,

I had a word with my work mates. I understand that you need to provide your own versions of a couple of CDT libraries since they won't allow you to overwrite certain classes (final). 

How about we approach the CDT team to remove the "final" keyword or ask for an "official" way to include your ProC plugin? I would support you on that. Also, this would relief you from adjusting CDT sources each time a release comes around.

If you like, contact me directly: m a i k . t o e p f e r @ b m w . d e   (remove spaces)

All the best and thank you for your great work.

**Comment by buntatsu** [comment]
Dear samba2,
Thanks for the suggestion.

In my clumsy English, because there is a need more time in the conversation itself, I did not approach the CDT team.

In particular, to remove the "final" is, because it is likely involved in their policy, seems to be the conversation becomes more difficult.

Do you have people good at Japanese near you? :-)

**Comment by samba2** [comment]
Dear Buntatsu,

I can support you with the communication. I am not a native speaker but have some experience writing technical English. 

Question: To get an idea about the changes required, could you please send me a list of the modifications required in the original sources? Is it really just one "final" which is removed or is there more to it? Maybe you can send me a "diff" of "original code" versus "your code"?

Many thanks,

Maik

**Comment by buntatsu** [comment]
Dear Maik,

Thanks a lot!

Changes are the following.
 - remove "final"
 - private -> protected
 - package private class -> public class
 - Inner class -> External class (to public)

I attached a diff file.

[CDT_8_8_1-modify.zip](https://github.com/buntatsu/cdt-proc/files/167168/CDT_8_8_1-modify.zip)

**Comment by gdsotirov** [comment]
I have the same problem with C/C++ indexer in Eclipse CDT Neon and cdt-proc 3.4.0. I see this thread froze 4 months ago, so I think I'll have to downgrade to Mars...

**Comment by buntatsu** [comment]
The error does not occur in my environment.
Did you try "eclipse.exe -clean" ?

**Comment by gdsotirov** [comment]
To answer your comment from 2016-07-17, no, I haven't tried `eclipse.exe -clean`, but I'm already with Neon.2 and the updated plugin, so there is no such problem anymore, so the issue could be closed.
